require_relative 'tony/tony'
require_relative 'tony/generator'
require_relative 'tony/generators/rspec/rspec_generator'
require_relative 'tony/generators/sinatra/sinatra_generator'
require_relative 'tony/generators/heroku/heroku_generator'
require_relative 'tony/generators/sinatra_rspec/sinatra_rspec_generator'
